# Generated by Django 6.0.5 on 2026-08-25 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('job_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('work_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], max_length=20)),
                ('job_type', models.CharField(blank=True, choices=[('internship', 'Internship'), ('coop', 'Co-op'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('pending', 'Pending'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='saved', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('company_website', 'Company Website'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('cold_email', 'Cold Email'), ('university', 'University Portal'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('resume_used', models.CharField(blank=True, max_length=150)),
                ('cover_letter_used', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_16fc9d_idx'), models.Index(fields=['user', 'date_applied'], name='application_user_id_3f3631_idx'), models.Index(fields=['user', 'follow_up_date'], name='application_user_id_6d21a8_idx')],
            },
        ),
    ]
